name = "sos-estresse"
account_id = "05feea1b04fbc55fff1361e6ff1f8559"
workers_dev = true
compatibility_date = "2026-07-29"
main = "_worker.js"

[assets]
directory = "./"
binding = "ASSETS"
html_handling = "none"
